apiVersion: v1 # for versions before 1.6.0 use extensions/v1beta1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: httpdserver
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  selector:
    name: privateweb
    app: httpd
  template:
    metadata:
      name: privateweb2
      labels:
        name: privateweb
        app: httpd
    spec:
      containers:
      - name: privateweb2
        image: uzzal2k5/httpd
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret
